return {
  { "jnurmine/Zenburn" },
  { "rebelot/kanagawa.nvim" },
  { "Shatur/neovim-ayu" },
  { "mhartington/oceanic-next" },
  { "sainnhe/gruvbox-material" },
  { "EdenEast/nightfox.nvim" },
  { "savq/melange-nvim" },
  { "folke/tokyonight.nvim" },
  { "altercation/vim-colors-solarized" },
  { "morhetz/gruvbox" },
  { "sainnhe/everforest" },
  { "doums/darcula" },
  { "lifepillar/vim-solarized8" },
  { "nvimdev/oceanic-material" },
  { "catppuccin/vim" },
  { "rose-pine/neovim" },
  { "Mofiqul/vscode.nvim" },
  { "lunacookies/vim-colors-xcode" },
  { "projekt0n/github-nvim-theme" },
  { "adibhanna/gruvdark.nvim" },
  { "NLKNguyen/papercolor-theme" },
  -- Configure LazyVim to load gruvbox
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "gruvbox-material",
    },
  },
}
